apiVersion: core.spinoperator.dev/v1
kind: SpinAppExecutor
metadata:
  name: containerd-shim-spin
  namespace: default
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "4"
spec:
