apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: hello-salutation-spinapp
spec:
  image: "ghcr.io/spinkube/spin-operator/salutations:20241105-223428-g4da3171"
  replicas: 1
  executor: containerd-shim-spin
  # Configure the application to only contain the "hello" component
  # Who doesn't hate goodbyes?
  components: ["hello"]
